import type { PetPortraitInterface } from "~/interfaces/PetPortrait";

export const data: ReadonlyArray<PetPortraitInterface> = [
  {
    id: 1,
    title: "Cat",
    image: "https://placekitten.com/200/300",
    altText: "A cat",
    dimensions: "A5",
    medium: "Coloured Pencil",
    surface: "Paper",
    date: new Date("2020-01-01"),
  },
  {
    id: 2,
    title: "Cat",
    image: "https://placekitten.com/250/301",
    altText: "A dog",
    dimensions: "A5",
    medium: "Coloured Pencil",
    surface: "Paper",
    date: new Date("2020-01-01"),
  },
  {
    id: 3,
    title: "Cat",
    image: "https://placekitten.com/200/302",
    altText: "A cat",
    dimensions: "A5",
    medium: "Coloured Pencil",
    surface: "Paper",
    date: new Date("2020-01-01"),
  },
  {
    id: 4,
    title: "Cat",
    image: "https://placekitten.com/200/303",
    altText: "A cat",
    dimensions: "A5",
    medium: "Graphite Pencil",
    surface: "Paper",
    date: new Date("2020-01-01"),
  },
  {
    id: 5,
    title: "Cat",
    image: "https://placekitten.com/200/304",
    altText: "A cat",
    dimensions: "A5",
    medium: "Coloured Pencil",
    surface: "Paper",
    date: new Date("2020-01-01"),
  },
  {
    id: 6,
    title: "Cat",
    image: "https://placekitten.com/200/305",
    altText: "A cat",
    dimensions: "A5",
    medium: "Coloured Pencil",
    surface: "Paper",
    date: new Date("2020-01-01"),
  },
  {
    id: 7,
    title: "Cat",
    image: "https://placekitten.com/200/306",
    altText: "A cat",
    dimensions: "A5",
    medium: "Coloured Pencil",
    surface: "Paper",
    date: new Date("2020-01-01"),
  },
];
